/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as RequirementsIndexRouteImport } from './routes/requirements.index'
import { Route as RequirementsIdRouteImport } from './routes/requirements.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsIndexRoute = RequirementsIndexRouteImport.update({
  id: '/requirements/',
  path: '/requirements/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsIdRoute = RequirementsIdRouteImport.update({
  id: '/requirements/$id',
  path: '/requirements/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/requirements/$id': typeof RequirementsIdRoute
  '/requirements/': typeof RequirementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/requirements/$id': typeof RequirementsIdRoute
  '/requirements': typeof RequirementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/requirements/$id': typeof RequirementsIdRoute
  '/requirements/': typeof RequirementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/documents' | '/requirements/$id' | '/requirements/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/documents' | '/requirements/$id' | '/requirements'
  id: '__root__' | '/' | '/documents' | '/requirements/$id' | '/requirements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  RequirementsIdRoute: typeof RequirementsIdRoute
  RequirementsIndexRoute: typeof RequirementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements/': {
      id: '/requirements/'
      path: '/requirements'
      fullPath: '/requirements/'
      preLoaderRoute: typeof RequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements/$id': {
      id: '/requirements/$id'
      path: '/requirements/$id'
      fullPath: '/requirements/$id'
      preLoaderRoute: typeof RequirementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  RequirementsIdRoute: RequirementsIdRoute,
  RequirementsIndexRoute: RequirementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
